name: Download and Upload to Release

on:
  repository_dispatch:
  workflow_dispatch:


jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}  # 输出上传地址 [[3, 9]]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1  # 使用社区维护的创建Release方案 [[11]]
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}

  upload-asset:
    needs: create-release  # 依赖创建Release的job [[9]]
    runs-on: ubuntu-latest
    steps:
    - name: Download File
      run: |
        curl -L -o ideaIU-2024.3.4.zip "https://cache-redirector.jetbrains.com/www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIU/2024.3.4/ideaIU-2024.3.4.zip"  # 下载外部文件 [[18]]
        
    - name: Upload Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url }}  # 获取上传地址 [[2, 9]]
        asset_path: ./ideaIU-2024.3.4.zip  # 本地文件路径
        asset_name: ideaIU-2024.3.4.zip  # 上传后的文件名
        asset_content_type: application/zip  # 文件类型 [[8]]
