name: Download and Upload to Release

on:
  repository_dispatch:
  workflow_dispatch:


jobs:
  upload-asset:
    runs-on: ubuntu-latest
    steps:
    - name: Download File
      run: |
        curl -L -o ideaIU-2024.3.4.zip "https://cache-redirector.jetbrains.com/www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIU/2024.3.4/ideaIU-2024.3.4.zip"  # 下载外部文件 [[18]]
    
    - name: 生成发布标签
      id: tag
      if: env.UPLOAD_RELEASE == 'true' && steps.compile.outputs.status == 'success' && !cancelled()
      run: |
        echo -e "xxxxxxx\n" >> release.txt
        echo "release_tag=$(date +"%Y.%m.%d_X86")" >> $GITHUB_OUTPUT
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload to releases
      uses: softprops/action-gh-release@v2.0.4
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: ideaIU-2024.3.4.zip
        body: ideaIU-2024.3.4.zip
        files: ideaIU-2024.3.4.zip
