name: Download and Upload to Release

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  download-and-upload:
    runs-on: ubuntu-latest
    steps:
    - name: Download File
      run: |
        # 使用curl下载文件（支持重定向）
        curl -L -o ideaIU-2024.3.4.zip "https://cache-redirector.jetbrains.com/www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIU/2024.3.4/ideaIU-2024.3.4.zip"
        
        # 可选：验证文件完整性
        echo "Checking file size..."
        ls -lh ideaIU-2024.3.4.zip

    - name: Upload to Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ideaIU-2024.3.4.zip  # 产物显示名称
        path: ideaIU-2024.3.4.zip     # 要上传的本地文件路径
        retention-days: 7         # 保留天数（默认90天）
